const APP_PREFIX = '#src';
const PREFIX = `${APP_PREFIX}/store/Account/`;

/**
 * Redux Constants
 */
export const GET_ACCOUNTS = `${PREFIX}GET_ACCOUNTS`;
export const GET_ACCOUNTS_SUCCESS = `${PREFIX}GET_ACCOUNTS_SUCCESS`;
export const GET_ACCOUNTS_FAIL = `${PREFIX}GET_ACCOUNTS_FAIL`;

export const DELETE_ACCOUNT = `${PREFIX}DELETE_ACCOUNT`;
export const DELETE_ACCOUNT_SUCCESS = `${PREFIX}DELETE_ACCOUNT_SUCCESS`;
export const DELETE_ACCOUNT_FAIL = `${PREFIX}DELETE_ACCOUNT_FAIL`;

export const GET_ACCOUNT_DETAIL = `${PREFIX}GET_ACCOUNT_DETAIL`;
export const GET_ACCOUNT_DETAIL_SUCCESS = `${PREFIX}GET_ACCOUNT_DETAIL_SUCCESS`;
export const GET_ACCOUNT_DETAIL_FAIL = `${PREFIX}GET_ACCOUNT_DETAIL_FAIL`;
